package com.example.coupontracker.schema

/**
 * Generates GBNF (GGML BNF) grammar from schema definitions.
 * GBNF is used by llama.cpp for constrained generation.
 */
object GBNFGenerator {
    
    /**
     * Generate complete GBNF grammar from schema
     */
    fun generate(schema: Schema): String {
        return buildString {
            appendLine("# Auto-generated GBNF grammar for ${schema.name}")
            appendLine("# Schema version: ${schema.version}")
            appendLine("# Generated by GBNFGenerator")
            appendLine()
            
            // Root rule
            append(generateRootRule(schema))
            appendLine()
            
            // Field rules
            schema.fields.forEach { field ->
                append(generateFieldRule(field))
                appendLine()
            }
            
            // Primitive rules
            append(generatePrimitiveRules())
        }
    }
    
    /**
     * Generate root rule defining the complete JSON structure
     */
    private fun generateRootRule(schema: Schema): String {
        return buildString {
            appendLine("root ::= \"{\" ws")
            
            schema.fields.forEachIndexed { index, field ->
                val separator = if (index > 0) "  \",\" ws" else ""
                if (separator.isNotEmpty()) {
                    appendLine(separator)
                }
                appendLine("  \"\\\"${field.name}\\\"\" ws \":\" ws ${field.name}-value")
            }
            
            appendLine("  ws \"}\"")
        }
    }
    
    /**
     * Generate rule for a specific field
     */
    private fun generateFieldRule(field: SchemaField): String {
        val valueName = "${field.name}-value"
        
        return when (field.type) {
            is FieldType.StringType -> {
                if (field.required) {
                    "$valueName ::= string"
                } else {
                    "$valueName ::= string | null"
                }
            }
            is FieldType.NumberType -> {
                if (field.required) {
                    "$valueName ::= number"
                } else {
                    "$valueName ::= number | null"
                }
            }
            is FieldType.BooleanType -> {
                if (field.required) {
                    "$valueName ::= boolean"
                } else {
                    "$valueName ::= boolean | null"
                }
            }
            is FieldType.DateType -> {
                // Dates are treated as strings
                if (field.required) {
                    "$valueName ::= string"
                } else {
                    "$valueName ::= string | null"
                }
            }
            is FieldType.EnumType -> {
                generateEnumRule(field.name, field.type.allowedValues, field.required)
            }
            is FieldType.ObjectType -> {
                generateObjectRule(field.name, field.type.properties, field.required)
            }
            is FieldType.ArrayType -> {
                generateArrayRule(field.name, field.type.itemType, field.required)
            }
            is FieldType.NullableType -> {
                "$valueName ::= string | number | boolean | null"
            }
        }
    }
    
    /**
     * Generate enum rule
     */
    private fun generateEnumRule(fieldName: String, allowedValues: List<String>, required: Boolean): String {
        val valueName = "$fieldName-value"
        val enumOptions = allowedValues.joinToString(" | ") { "\"\\\"$it\\\"\"" }
        
        return if (required) {
            "$valueName ::= $enumOptions"
        } else {
            "$valueName ::= $enumOptions | null"
        }
    }
    
    /**
     * Generate object rule (nested structure)
     */
    private fun generateObjectRule(
        fieldName: String,
        properties: Map<String, SchemaField>,
        required: Boolean
    ): String {
        return buildString {
            val valueName = "$fieldName-value"
            
            // Define object structure
            appendLine("$valueName ::= $fieldName-object" + if (!required) " | null" else "")
            
            appendLine("$fieldName-object ::= \"{\" ws")
            
            properties.entries.forEachIndexed { index, (propName, propField) ->
                val separator = if (index > 0) "  \",\" ws" else ""
                if (separator.isNotEmpty()) {
                    appendLine(separator)
                }
                
                val propRuleName = "$fieldName-$propName"
                appendLine("  \"\\\"$propName\\\"\" ws \":\" ws $propRuleName")
                
                // Define property rule inline
                val propRule = when (propField.type) {
                    is FieldType.StringType -> if (propField.required) "string" else "string | null"
                    is FieldType.NumberType -> if (propField.required) "number" else "number | null"
                    is FieldType.BooleanType -> if (propField.required) "boolean" else "boolean | null"
                    is FieldType.EnumType -> {
                        val options = propField.type.allowedValues.joinToString(" | ") { "\"\\\"$it\\\"\"" }
                        if (propField.required) options else "$options | null"
                    }
                    else -> "string | number | boolean | null"
                }
                appendLine("$propRuleName ::= $propRule")
            }
            
            append("  ws \"}\"")
        }
    }
    
    /**
     * Generate array rule
     */
    private fun generateArrayRule(fieldName: String, itemType: FieldType, required: Boolean): String {
        val valueName = "$fieldName-value"
        val itemRule = when (itemType) {
            is FieldType.StringType -> "string"
            is FieldType.NumberType -> "number"
            is FieldType.BooleanType -> "boolean"
            else -> "string | number | boolean"
        }
        
        return buildString {
            appendLine("$valueName ::= $fieldName-array" + if (!required) " | null" else "")
            appendLine("$fieldName-array ::= \"[\" ws ($fieldName-item (\",\" ws $fieldName-item)*)? ws \"]\"")
            append("$fieldName-item ::= $itemRule")
        }
    }
    
    /**
     * Generate primitive type rules (string, number, boolean, null, whitespace)
     */
    private fun generatePrimitiveRules(): String {
        return """
# Primitive types
string ::= "\"" ([^"\\\x00-\x1f] | "\\" (["\\\/bfnrt] | "u" [0-9a-fA-F]{4}))* "\""
number ::= "-"? ("0" | [1-9] [0-9]*) ("." [0-9]+)? ([eE] [+-]? [0-9]+)?
boolean ::= "true" | "false"
null ::= "null"
ws ::= [ \t\n\r]*
        """.trimIndent()
    }
    
    /**
     * Validate that generated grammar has required elements
     */
    fun validateGrammar(grammar: String): Boolean {
        return grammar.contains("root ::=") &&
               grammar.contains("string ::=") &&
               grammar.contains("number ::=") &&
               grammar.contains("ws ::=")
    }
    
    /**
     * Format grammar with consistent indentation
     */
    fun formatGrammar(grammar: String): String {
        return grammar.lines()
            .joinToString("\n") { line ->
                when {
                    line.startsWith("#") -> line // Comments unchanged
                    line.trim().isEmpty() -> "" // Blank lines
                    line.startsWith(" ") -> line // Already indented
                    else -> line // Top-level rules
                }
            }
    }
}

