#!/bin/bash
# Automated Repository Cleanup Script
# Generated by analyze_unnecessary_files.py

echo "🧹 Starting repository cleanup..."

# Remove build artifacts
echo "🏗️  Removing build artifacts..."
rm -rf app/build/
rm -rf app/.cxx/
rm -rf .gradle/
find . -name "*.apk" -delete
find . -name "*.aab" -delete

# Remove cache files
echo "💾 Removing cache files..."
find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null
find . -name "*.pyc" -delete
find . -name "*.pyo" -delete
find . -name ".DS_Store" -delete
find . -name "Thumbs.db" -delete

# Remove log files
echo "📝 Removing log files..."
find . -name "*.log" -delete
rm -rf logs/

# Remove development artifacts
echo "🔧 Removing development artifacts..."
rm -f smoke_test_results.json
rm -f evaluation_results.json
rm -f deployment_validation_metrics.json

# Remove temporary files
echo "🗑️  Removing temporary files..."
find . -name "*~" -delete
find . -name "*.bak" -delete
find . -name "*.swp" -delete
find . -name "*.orig" -delete

echo "✅ Cleanup completed!"
echo "📊 Run 'du -sh .' to check new repository size"
